Correctly catch failure

diff --git a/core/9x8/peripherals/tb/runall b/core/9x8/peripherals/tb/runall
--- a/core/9x8/peripherals/tb/runall
+++ b/core/9x8/peripherals/tb/runall
@@ -4,11 +4,10 @@
 #
 # Run all of the test benches for the peripherals.
 
-find -name run | while read runname; do
-  (
-    cd  ${runname:0:${#runname}-4};
-    ./run || exit 1;
-  )
+for runname in `find -name run`; do
+  cd  ${runname:0:${#runname}-4};
+  ./run || { echo "Tests aborted"; exit 1; }
+  cd ..
 done
 
 echo "All tests passed!";
