Use hard-wire paths instead of soft links for "ssbcc"

diff --git a/lib/9x8/tb/char/run b/lib/9x8/tb/char/run
--- a/lib/9x8/tb/char/run
+++ b/lib/9x8/tb/char/run
@@ -4,10 +4,7 @@
 
 NAME="char";
 
-rm --force ssbcc;
-ln -s ../../../../ssbcc;
-
-./ssbcc -q --display-opcode -P monitor_stack uc.9x8 || { echo "FATAL ERROR testing ${NAME}" > /dev/stderr; exit 1; }
+../../../../ssbcc -q --display-opcode -P monitor_stack uc.9x8 || { echo "FATAL ERROR testing ${NAME}" > /dev/stderr; exit 1; }
 iverilog -o tb tb.v uc.v || exit 1;
 if [ -n "`./tb | cmp - "tb.good" 2>&1`" ]; then
   echo "${NAME} failed" > /dev/stderr;
@@ -15,4 +12,4 @@ if [ -n "`./tb | cmp - "tb.good" 2>&1`" ]; then
 fi
 echo "Passed:  ${NAME}";
 
-rm --force ssbcc uc.9x8-meta uc.v tb;
+rm --force uc.9x8-meta uc.v tb;
diff --git a/lib/9x8/tb/math/run b/lib/9x8/tb/math/run
--- a/lib/9x8/tb/math/run
+++ b/lib/9x8/tb/math/run
@@ -4,10 +4,7 @@
 
 NAME="math";
 
-rm --force ssbcc;
-ln -s ../../../../ssbcc;
-
-./ssbcc -q -P monitor_stack --display-opcode uc.9x8 || { echo "FATAL ERROR testing ${NAME}" > /dev/stderr; exit 1; }
+../../../../ssbcc -q -P monitor_stack --display-opcode uc.9x8 || { echo "FATAL ERROR testing ${NAME}" > /dev/stderr; exit 1; }
 iverilog -o tb tb.v uc.v || exit 1;
 if [ -n "`./tb | gawk -f tb.awk`" ]; then
   echo "${NAME} failed" > /dev/stderr;
@@ -15,4 +12,4 @@ if [ -n "`./tb | gawk -f tb.awk`" ]; then
 fi
 echo "Passed:  ${NAME}";
 
-#rm --force ssbcc uc.9x8-meta uc.v tb;
+rm --force uc.9x8-meta uc.v tb;
