Incorporate modified ../libi2c.s and restructure to match ../TCA9554

diff --git a/example/i2c/TMP100/Xilinx-SP601/make b/example/i2c/TMP100/Xilinx-SP601/make
--- a/example/i2c/TMP100/Xilinx-SP601/make
+++ b/example/i2c/TMP100/Xilinx-SP601/make
@@ -1,6 +1,11 @@
 #!/bin/sh
 #
 # Make script for SP601 board.
+#
+# Usage:
+#   ./make |& tee log
+
+source /opt/Xilinx/14.7/ISE_DS/settings64.sh
 
 # Ensure the script to build the micro processor is present.
 if [ -n "`which ssbcc | sed -n -e '/^which:/p'`" ]; then
@@ -17,7 +22,7 @@ NAME=sp601
 DEVICE=xc6slx16-2-csg324
 
 FILES="";
-FILES+=" ../../i2c_tmp100.v";
+FILES+=" ../uc/i2c_tmp100.v";
 FILES+=" ${NAME}.v";
 
 #
@@ -25,7 +30,7 @@ FILES+=" ${NAME}.v";
 #
 
 # Build the micro processor.
-( cd ../..; ssbcc --define-clog i2c_tmp100.9x8 ) || exit 1;
+( cd ../uc; ssbcc --define-clog i2c_tmp100.9x8 ) || { echo "SSBCC failed" > /dev/stderr; exit 1; }
 
 #
 # Configure and run the synthesis
@@ -96,7 +101,7 @@ EOF
 xst \
   -ifn "${NAME}.xst" \
   -ofn "${NAME}.syr" \
-|| { echo "XST Failed!"; exit 1; }
+|| { echo "XST Failed!" > /dev/stderr; exit 1; }
 
 #
 # Run through PAR
@@ -108,7 +113,7 @@ ngdbuild \
   -uc ${NAME}.ucf \
   -p ${DEVICE} \
   ${NAME}.ngc ${NAME}.ngd \
-|| { echo "ngdbuild Failed!"; exit 1; }
+|| { echo "ngdbuild Failed!" > /dev/stderr; exit 1; }
 
 map \
   -p ${DEVICE} \
@@ -127,14 +132,14 @@ map \
   -power off \
   -o ${NAME}.ncd \
   ${NAME}.ngd ${NAME}.pcf \
-|| { echo "MAP Failed!"; exit 1; }
+|| { echo "MAP Failed!" > /dev/stderr; exit 1; }
 
 par \
   -w \
   -ol high \
   -mt off \
   ${NAME}.ncd ${NAME}.ncd ${NAME}.pcf \
-|| { echo "PAR Failed!"; exit 1; }
+|| { echo "PAR Failed!" > /dev/stderr; exit 1; }
 
 #
 # Optionally perform timing analysis
@@ -191,4 +196,4 @@ cat <<EOF >${NAME}.ut
 EOF
 
 bitgen -f ${NAME}.ut ${NAME}.ncd \
-|| { echo "BITGEN Failed!"; exit 1; }
+|| { echo "BITGEN Failed!" > /dev/stderr; exit 1; }
